import { Router } from 'express';
import auditRoutes from './auditRoutes.js';
import authRoutes from './authRoutes.js';
import billingRoutes from '../modules/billing/routes.js';
import customerRoutes from './customerRoutes.js';
import documentRoutes from '../modules/documents/routes.js';
import draftRoutes from './draftRoutes.js';
import expenseRoutes from '../modules/expenses/routes.js';
import exportRoutes from '../modules/exports/routes.js';
import gstRoutes from '../modules/gst/routes.js';
import importRoutes from '../modules/imports/routes.js';
import invoiceRoutes from './invoiceRoutes.js';
import ledgerRoutes from './ledgerRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import onboardingRoutes from './onboardingRoutes.js';
import orderRoutes from './orderRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import productRoutes from './productRoutes.js';
import purchaseRoutes from '../modules/purchases/routes.js';
import publicRoutes from './publicRoutes.js';
import reportRoutes from './reportRoutes.js';
import roleRoutes from './roleRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import syncRoutes from '../modules/sync/routes.js';
import teamRoutes from './teamRoutes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/billing', billingRoutes);
router.use('/products', productRoutes);
router.use('/customers', customerRoutes);
router.use('/documents', documentRoutes);
router.use('/drafts', draftRoutes);
router.use('/expenses', expenseRoutes);
router.use('/exports', exportRoutes);
router.use('/gst', gstRoutes);
router.use('/imports', importRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/notifications', notificationRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/public', publicRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/reports', reportRoutes);
router.use('/roles', roleRoutes);
router.use('/settings', settingsRoutes);
router.use('/sync', syncRoutes);
router.use('/team', teamRoutes);

export default router;
